articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete')
]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView


app_name = 'likeapp'

urlpatterns = [
    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like'),
]

web0701_/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),

    path('subscibes/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 어떤 경로로 요청이 들어왔을 때 / 어디서 파일을 제공해줄건지

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User,
                               on_delete=models.SET_NULL,
                               related_name='article',
                               null=True)
    project = models.ForeignKey(Project,
                                on_delete=models.SET_NULL,
                                related_name='article',
                                null=True, blank=True)
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=True)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)
    like = models.IntegerField(default=0)

templates/snippets/list_fragment.html
{% load static %}



    <style>

        .container {
            padding: 0;
            margin: 0 auto;
        }

        .container div {
          width: 45%;
            max-width: 200px;
            box-shadow: 0 0 .5rem grey;
          display: flex;
          justify-content: center;
          align-items: center;
          border-radius: 1rem;
            flex-direction: column;
        }

        .container img {
            width: 100%;
            border-radius: 1rem;
        }

    </style>


    <div class="container my-4">

        {% for article in article_list %}

            <div>
                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    <img src="{{ article.image.url }}"
                         alt="">
                </a>
                <span>{{ article.title }}</span>
            </div>

        {% endfor %}

    </div>

    <script src="{% static 'js/magicgrid.js' %}"></script>

   {% include 'snippets/pagination.html' %}

    <div class="text-center my-5">
        <a href="{% url 'articleapp:create' %}"
            class="btn btn-dark rounded-pill material-icons">
                brush
        </a>
        <a href="{% url 'articleapp:create' %}"
                class="btn btn-outline-dark rounded-pill px-5">
            Create Article
        </a>
    </div>

templates/snippets/pagination.html
 <div class="text-center my-4">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}"
                class="btn btn-secondary rounded-pill">
                {{ page_obj.previous_page_number }}
            </a>
        {% endif %}
        <a href="#"
            class="btn btn-dark rounded-pill NNS_B">
            {{ page_obj.number }}
        </a>
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"
                class="btn btn-secondary rounded-pill">
                {{ page_obj.next_page_number }}
            </a>
        {% endif %}
    </div>